# Generated by Django 5.1.6 on 2025-03-01 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.PositiveBigIntegerField()),
                ('is_freelance', models.BooleanField()),
                ('designation', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('total_project', models.IntegerField()),
                ('profile_picture', models.ImageField(upload_to='profile_picture')),
                ('description', models.TextField()),
                ('experience', models.IntegerField()),
                ('resume', models.FileField(upload_to='documents/')),
                ('my_award_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Personal Information',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='service/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_icon', models.ImageField(upload_to='award_icon/')),
                ('award_title', models.CharField(max_length=100)),
                ('award_name', models.CharField(max_length=100)),
                ('award_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('college_name', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=150)),
                ('job', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_experience', to='pages.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tools', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=80)),
                ('overview', models.TextField()),
                ('image', models.ImageField(upload_to='project/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('skill_icon', models.ImageField(upload_to='skill_icon/')),
                ('percentage', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('UI/UX', 'UI/UX'), ('Web Developement', 'Web Developement'), ('Mobile App', 'Mobile App'), ('AI', 'AI')], max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.project')),
            ],
        ),
    ]
